  "model":
    "type": "DFNet"
    "params":
      "in_channels": 4  # RGB (3) + Simulated Depth (1)
      "hidden_channels": 64
      "L": 5
      "k": 12

  "optimizer":
    "type": "AdamW"
    "params":
      "lr": 0.001

  "lr_scheduler":
    "type": "MultiStepLR"
    "params":
      "milestones": [5, 15, 25, 35]
      "gamma": 0.2

  "dataset":
    "train":
      "type": "surgical_depth"
      "data_dir": "data"
      "root_dir": "/home/beltagy/Desktop/master_thesis/BlenderProc/examples/datasets/OP_room/output_group"
      "rgb_dir": "data/rgb"
      "sim_depth_dir": "data/simulated_depth"
      "gt_depth_dir": "data/perfect_depth"
      "image_size": !!python/tuple [320, 240]
      "use_augmentation": True
      "rgb_augmentation_probability": 0.8
      "depth_min": 0.2
      "depth_max": 2.0
      "depth_norm": 1.0
      "with_original": True
    "test":
      "type": "surgical_depth"
      "data_dir": "data"
      "root_dir": "/home/beltagy/Desktop/master_thesis/BlenderProc/examples/datasets/OP_room/output_group_test"
      "rgb_dir": "data/rgb"
      "sim_depth_dir": "data/simulated_depth"
      "gt_depth_dir": "data/perfect_depth"
      "image_size": !!python/tuple [320, 240]
      "use_augmentation": False
      "depth_min": 0.2    # update to match with our data set
      "depth_max": 2.0
      "depth_norm": 1.0
      "with_original": True

  "dataloader":
    "num_workers": 8
    "shuffle": True
    "drop_last": True

  "trainer":
    "batch_size": 32
    "test_batch_size": 1
    "multigpu": True
    "max_epoch": 40  
    "criterion":
      # "type": "custom_masked_l1_loss"
      "type": "custom_masked_mse_loss"
      "epsilon": 0.00000001
      "combined_smooth": True
      "combined_beta": 0.001

  "metrics":
    "types": ["MSE", "MaskedMSE", "RMSE", "MaskedRMSE", "REL", "MaskedREL", "MAE", "MaskedMAE", "Threshold@1.05", "MaskedThreshold@1.05", "Threshold@1.10", "MaskedThreshold@1.10", "Threshold@1.25", "MaskedThreshold@1.25"]
    "epsilon": 0.00000001
    "depth_scale": 1.0

  "stats":
    "stats_dir": "stats"
    "stats_exper": "train-surgical-depth"
