"model":
  "type": "SwinDRNet"
  "params":
    "config":
      "DATA":
        "IMG_SIZE": 224
      "TRAIN":
        "USE_CHECKPOINT" : False 
      "MODEL":
        "TYPE": swin
        "NAME": swin_tiny_patch4_window7_224
        "DROP_RATE" : 0.0
        # Label Smoothing
        "LABEL_SMOOTHING" : 0.1

        "DROP_PATH_RATE": 0.2
        # "PRETRAIN_CKPT": "pretrained_model/swin_tiny_patch4_window7_224.pth"
        "SWIN":
          "FINAL_UPSAMPLE": "expand_first"
          "EMBED_DIM": 96
          "DEPTHS": [ 2, 2, 6, 2 ]
          "DECODER_DEPTHS": [ 2, 2, 2, 1]
          "NUM_HEADS": [ 3, 6, 12, 24 ]
          "WINDOW_SIZE": 7
          "PATCH_SIZE" : 4
          "IN_CHANS" : 3
          "EMBED_DIM" : 96
          "DEPTHS" : [2, 2, 6, 2]
          "DECODER_DEPTHS" : [2, 2, 6, 2]
          "NUM_HEADS" : [3, 6, 12, 24]
          "WINDOW_SIZE" : 7
          "MLP_RATIO" : 4.
          "QKV_BIAS" : True
          "QK_SCALE" : None
          "APE" : False
          "PATCH_NORM" : True
          "FINAL_UPSAMPLE": "expand_first"

"inference":
  "checkpoint_path": "stats/train-surgical-depthDREDS/checkpoint.tar"
  "image_size": !!python/tuple [320, 240]
  "cuda_id": 0
  "depth_min": 0.1
  "depth_max": 2.0
  "depth_norm": 1.0
